---
interfaces:
  Ethernet 112:
      - ip: 192.168.1.4/31
  Ethernet 40:
      - ip: 192.168.1.8/31
  Ethernet 4:
      - ip: 110.1.1.3/24
  Loopback 0:
      - ip: 100.1.1.4/32
  Ethernet 0:
      - channel_grp: 1

mclag:
  source_ip: 110.1.1.3
  peer_ip: 110.1.1.4

bgp:
  asn: 65013
  remote_asn:
    - 65012
  neighbor_1_ip: 192.168.1.10
  neighbor_2_ibgp_ip: 192.168.1.9
  neighbor_1_source_ip: 100.1.1.1
