---
interfaces:
  Ethernet 112:
      - ip: 192.168.1.1/31
  Ethernet 40:
      - ip: 192.168.1.6/31
  Ethernet 4:
      - ip: 110.1.1.1/24
  Loopback 0:
      - ip: 100.1.1.2/32
  Ethernet 0:
      - channel_grp: 1

mclag:
  source_ip: 110.1.1.1
  peer_ip: 110.1.1.2

bgp:
  asn: 65011
  remote_asn:
    - 65012
  neighbor_1_ip: 192.168.1.0
  neighbor_2_ibgp_ip: 192.168.1.7
  neighbor_1_source_ip: 100.1.1.1
