---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
     - edgecore.sonic
  tasks:
    - name: "Test patch_api"
      sonic_api:
        url: data/openconfig-interfaces:interfaces/interface=Ethernet64/config/description
        method: "PATCH"
        status_code: 204
        body: {"openconfig-interfaces:description": "hi "}
    - name: "Test patch_api"
      sonic_api:
        url: data/openconfig-interfaces:interfaces/interface=Ethernet64/subinterfaces/subinterface=0/openconfig-if-ip:ipv4/
        method: "PATCH"
        status_code: 204
        body: "{{ lookup('file','../tests/regression/sonic_api/patch.txt') }}"
