---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: True
  connection: httpapi
  collections:
    - edgecore.sonic
  tasks:
    - name: "Test gather facts"
      sonic_facts:
        gather_subset: min
        gather_network_resources: interfaces
      register: result
      
    - name: "debug facts"
      debug: 
        msg: "{{ result.ansible_facts.ansible_network_resources }}"
